config_rewrite: replace
langcode: en
status: true
dependencies:
  enforced:
    module:
      - book
  module:
    - menu_ui
third_party_settings:
  menu_ui:
    available_menus:
      - main
    parent: 'main:'
name: 'Book page'
type: book
description: '<em>Books</em> have a built-in hierarchical navigation. Use for handbooks or tutorials.'
help: ''
new_revision: true
preview_mode: 1
display_submitted: false
