config_rewrite: replace
langcode: en
status: true
dependencies:
  module:
    - node
_core:
  default_config_hash: dccI0aMqbCYWOoBgpP2KeCRjxBV0AjmqzvASrmkLtSc
label: Default
id: default
description: 'A default Linkit profile'
matchers:
  556010a3-e317-48b3-b4ed-854c10f4b950:
    id: 'entity:node'
    uuid: 556010a3-e317-48b3-b4ed-854c10f4b950
    settings:
      metadata: 'by [node:author] | [node:created:medium]'
      bundles: {  }
      group_by_bundle: false
      include_unpublished: false
      substitution_type: canonical
      limit: 100
    weight: 0
