config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - field.field.node.blog_post.body
    - field.field.node.blog_post.field_avatar_image
    - field.field.node.blog_post.field_blog_comments
    - field.field.node.blog_post.field_blog_tags
    - field.field.node.blog_post.field_image
    - field.field.node.blog_post.field_meta_tags
    - image.style.thumbnail
    - node.type.blog_post
  module:
    - comment
    - content_moderation
    - image
    - metatag
    - path
    - text
id: node.blog_post.default
targetEntityType: node
bundle: blog_post
mode: default
content:
  body:
    type: text_textarea_with_summary
    weight: 9
    settings:
      rows: 9
      summary_rows: 3
      placeholder: ''
    third_party_settings: {  }
    region: content
  created:
    type: datetime_timestamp
    weight: 3
    settings: {  }
    third_party_settings: {  }
    region: content
  field_avatar_image:
    type: entity_browser_file
    weight: 10
    settings:
      entity_browser: image_browser
      field_widget_edit: true
      field_widget_remove: true
      view_mode: default
      preview_image_style: thumbnail
      open: true
      selection_mode: selection_append
    region: content
    third_party_settings: {  }
  field_blog_comments:
    weight: 12
    settings: {  }
    third_party_settings: {  }
    type: comment_default
    region: content
  field_blog_tags:
    weight: 13
    settings:
      match_operator: CONTAINS
      size: 60
      placeholder: ''
    third_party_settings: {  }
    type: entity_reference_autocomplete
    region: content
  field_image:
    type: entity_browser_file
    weight: 11
    settings:
      entity_browser: image_browser
      field_widget_edit: true
      field_widget_remove: true
      view_mode: default
      preview_image_style: thumbnail
      open: true
      selection_mode: selection_append
    region: content
    third_party_settings: {  }
  field_meta_tags:
    type: metatag_firehose
    weight: 5
    region: content
    settings: {  }
    third_party_settings: {  }
  langcode:
    type: language_select
    weight: 1
    region: content
    settings:
      include_locked: true
    third_party_settings: {  }
  path:
    type: path
    weight: 8
    settings: {  }
    third_party_settings: {  }
    region: content
  promote:
    type: boolean_checkbox
    settings:
      display_label: true
    weight: 6
    third_party_settings: {  }
    region: content
  sticky:
    type: boolean_checkbox
    settings:
      display_label: true
    weight: 7
    third_party_settings: {  }
    region: content
  title:
    type: string_textfield
    weight: 0
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
    region: content
  translation:
    weight: 4
    region: content
    settings: {  }
    third_party_settings: {  }
  uid:
    type: entity_reference_autocomplete
    weight: 2
    settings:
      match_operator: CONTAINS
      size: 60
      placeholder: ''
    third_party_settings: {  }
    region: content
hidden:
  status: true
