config_rewrite: replace
langcode: en
status: true
dependencies:
  module:
    - menu_ui
    - workbench_moderation
third_party_settings:
  menu_ui:
    available_menus: {  }
    parent: 'main:'
  workbench_moderation:
    enabled: true
    allowed_moderation_states:
      - published
      - archived
      - draft
      - needs_review
    default_moderation_state: draft
name: 'Blog post'
type: blog_post
description: 'Use for multi-user blogs. Every user gets a personal blog.'
help: ''
new_revision: true
preview_mode: 0
display_submitted: false
