hidden:
  langcode: true
  panelizer: true
third_party_settings:
  panelizer:
    enable: true
    custom: true
    displays:
      default:
        blocks:
          197a21c8-479d-4d6b-9a05-5eaaf82b0e0e:
            id: 'entity_field:node:body'
            label: Body
            provider: ctools_block
            label_display: '0'
            formatter:
              label: hidden
              type: text_default
              settings: {  }
              third_party_settings: {  }
              weight: 0
            context_mapping:
              entity: '@panelizer.entity_context:entity'
            region: middle
            weight: 1
            uuid: 197a21c8-479d-4d6b-9a05-5eaaf82b0e0e
        id: panels_variant
        uuid: df0d1b37-8cd5-46d3-b900-f18df4825325
        label: ''
        weight: 0
        layout: onecol
        layout_settings: {  }
        page_title: '[node:title]'
        storage_type: panelizer_default
        storage_id: 'node:page:full:default'
        builder: ipe
