config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.node.full
    - field.field.node.landing_page.body
    - field.field.node.landing_page.field_meta_tags
    - field.field.node.landing_page.field_queue
    - field.field.node.landing_page.layout_builder__layout
    - field.field.node.landing_page.layout_builder__translation
    - field.field.node.landing_page.layout_selection
    - field.field.node.page.body
    - node.type.landing_page
    - system.menu.account
  module:
    - bootstrap_layouts
    - layout_builder
    - layout_library
    - metatag
    - panelizer
    - system
    - user
third_party_settings:
  panelizer:
    enable: false
    custom: false
    displays:
      default:
        blocks:
          398ddd2d-fe84-40e8-9120-37bc2e866efa:
            id: page_title_block
            label: 'Page title'
            provider: core
            label_display: '0'
            region: main
            weight: -1
            uuid: 398ddd2d-fe84-40e8-9120-37bc2e866efa
            context_mapping: {  }
          d32f81b0-722f-4094-9397-e508fce0be86:
            id: local_tasks_block
            label: Tabs
            provider: core
            label_display: '0'
            primary: true
            secondary: true
            region: main
            weight: 0
            uuid: d32f81b0-722f-4094-9397-e508fce0be86
            context_mapping: {  }
          53c78586-ebb9-4749-b0f4-7b0846043c9d:
            id: 'entity_field:node:body'
            label: Body
            provider: ctools_block
            label_display: '0'
            formatter:
              label: above
              type: text_default
              settings: {  }
              third_party_settings: {  }
              weight: 0
            region: main
            weight: 1
            uuid: 53c78586-ebb9-4749-b0f4-7b0846043c9d
            context_mapping:
              entity: '@panelizer.entity_context:entity'
        id: panels_variant
        uuid: 1a312aa0-75a2-4467-8421-33670a7bd039
        label: 'Single Column'
        weight: 0
        layout: bs_1col
        layout_settings:
          layout:
            wrapper: div
            classes:
              row: row
            add_layout_class: 1
            attributes: ''
          regions:
            main:
              wrapper: div
              classes:
                col-sm-12: col-sm-12
              add_region_classes: 1
              attributes: ''
        page_title: '[node:title]'
        storage_type: panelizer_default
        storage_id: 'node:landing_page:full:default'
        pattern: panelizer
        builder: ipe
        static_context: {  }
      two_column:
        blocks:
          2ba0359c-af3f-4bd7-a6d6-a6e93f680883:
            id: 'entity_field:node:body'
            label: Body
            provider: ctools_block
            label_display: '0'
            formatter:
              label: hidden
              type: text_default
              settings: {  }
              third_party_settings: {  }
              weight: 0
            region: top_right
            weight: 1
            uuid: 2ba0359c-af3f-4bd7-a6d6-a6e93f680883
            context_mapping:
              entity: '@panelizer.entity_context:entity'
          62dd7b94-9f49-4b61-ad40-f65d365a7f46:
            id: page_title_block
            label: 'Page title'
            provider: core
            label_display: visible
            region: top_right
            weight: -1
            uuid: 62dd7b94-9f49-4b61-ad40-f65d365a7f46
            context_mapping: {  }
          e58e904b-8890-4559-9582-222b7ca445a9:
            id: local_tasks_block
            label: Tabs
            provider: core
            label_display: '0'
            primary: true
            secondary: true
            region: top_right
            weight: 0
            uuid: e58e904b-8890-4559-9582-222b7ca445a9
            context_mapping: {  }
          e18fc4d1-7588-47ae-97b7-69379a6f2e0d:
            id: 'system_menu_block:account'
            label: 'User account menu'
            provider: system
            label_display: visible
            level: 1
            depth: 0
            region: top_left
            weight: -1
            uuid: e18fc4d1-7588-47ae-97b7-69379a6f2e0d
            context_mapping: {  }
        id: panels_variant
        uuid: 91b9d430-7b91-4a22-ac4d-2e5e0376c6a2
        label: 'Two Column'
        weight: 0
        layout: bs_2col_bricked
        layout_settings:
          layout:
            wrapper: div
            classes:
              row: row
            add_layout_class: 1
            attributes: ''
          regions:
            top:
              wrapper: div
              classes:
                col-sm-12: col-sm-12
              add_region_classes: 1
              attributes: 'class|mrgn-tp-lg,class|mrgn-bttm-lg'
            top_left:
              wrapper: div
              classes:
                col-md-3: col-md-3
              add_region_classes: 1
              attributes: ''
            top_right:
              wrapper: div
              classes:
                col-md-9: col-md-9
              add_region_classes: 1
              attributes: ''
            middle:
              wrapper: div
              classes:
                col-sm-12: col-sm-12
              add_region_classes: 1
              attributes: ''
            bottom_left:
              wrapper: div
              classes:
                col-sm-6: col-sm-6
              add_region_classes: 1
              attributes: ''
            bottom_right:
              wrapper: div
              classes:
                col-sm-6: col-sm-6
              add_region_classes: 1
              attributes: ''
            bottom:
              wrapper: div
              classes:
                col-sm-12: col-sm-12
              add_region_classes: 1
              attributes: ''
        page_title: '[node:title]'
        storage_type: panelizer_default
        storage_id: 'node:landing_page:full:two_column'
        pattern: panelizer
        builder: ipe
        static_context: {  }
      three_column:
        blocks:
          5ad36b60-5439-4e3f-bb62-bb504ba9e67a:
            id: page_title_block
            label: 'Page title'
            provider: core
            label_display: '0'
            region: middle
            weight: -1
            uuid: 5ad36b60-5439-4e3f-bb62-bb504ba9e67a
            context_mapping: {  }
          75029cf4-e12d-4af2-9c8d-a6d9a97ded82:
            id: local_tasks_block
            label: Tabs
            provider: core
            label_display: '0'
            primary: true
            secondary: true
            region: middle
            weight: 0
            uuid: 75029cf4-e12d-4af2-9c8d-a6d9a97ded82
            context_mapping: {  }
          45da81c5-2c0e-4903-acab-76f999c4cb66:
            id: 'entity_field:node:body'
            label: Body
            provider: ctools_block
            label_display: '0'
            formatter:
              label: above
              type: text_default
              settings: {  }
              third_party_settings: {  }
              weight: 0
            region: middle
            weight: 1
            uuid: 45da81c5-2c0e-4903-acab-76f999c4cb66
            context_mapping:
              entity: '@panelizer.entity_context:entity'
        id: panels_variant
        uuid: 5af47416-fa98-4dfb-9761-fc497a47a76f
        label: 'Three Column'
        weight: 0
        layout: bs_3col_bricked
        layout_settings:
          layout:
            wrapper: div
            classes:
              row: row
            add_layout_class: 1
            attributes: ''
          regions:
            top:
              wrapper: div
              classes:
                col-sm-12: col-sm-12
              add_region_classes: 1
              attributes: ''
            top_left:
              wrapper: div
              classes:
                col-sm-4: col-sm-4
              add_region_classes: 1
              attributes: ''
            top_middle:
              wrapper: div
              classes:
                col-sm-4: col-sm-4
              add_region_classes: 1
              attributes: ''
            top_right:
              wrapper: div
              classes:
                col-sm-4: col-sm-4
              add_region_classes: 1
              attributes: ''
            middle:
              wrapper: div
              classes:
                col-sm-4: col-sm-4
              add_region_classes: 1
              attributes: ''
            bottom_left:
              wrapper: div
              classes:
                col-sm-4: col-sm-4
              add_region_classes: 1
              attributes: ''
            bottom_middle:
              wrapper: div
              classes:
                col-sm-4: col-sm-4
              add_region_classes: 1
              attributes: ''
            bottom_right:
              wrapper: div
              classes:
                col-sm-4: col-sm-4
              add_region_classes: 1
              attributes: ''
            bottom:
              wrapper: div
              classes:
                col-sm-12: col-sm-12
              add_region_classes: 1
              attributes: ''
        page_title: '[node:title]'
        storage_type: panelizer_default
        storage_id: 'node:landing_page:full:three_column'
        pattern: panelizer
        builder: ipe
        static_context: {  }
    allow: false
    default: two_column
  layout_builder:
    allow_custom: true
    enabled: true
    sections:
      -
        layout_id: bs_2col_bricked
        layout_settings:
          layout:
            wrapper: div
            classes:
              row: row
            add_layout_class: 1
            attributes: ''
          regions:
            top:
              wrapper: div
              classes:
                col-sm-12: col-sm-12
              add_region_classes: 1
              attributes: 'class|mrgn-tp-lg,class|mrgn-bttm-lg'
            top_left:
              wrapper: div
              classes:
                col-md-3: col-md-3
              add_region_classes: 1
              attributes: ''
            top_right:
              wrapper: div
              classes:
                col-md-9: col-md-9
              add_region_classes: 1
              attributes: ''
            middle:
              wrapper: div
              classes:
                col-sm-12: col-sm-12
              add_region_classes: 1
              attributes: ''
            bottom_left:
              wrapper: div
              classes:
                col-sm-6: col-sm-6
              add_region_classes: 1
              attributes: ''
            bottom_right:
              wrapper: div
              classes:
                col-sm-6: col-sm-6
              add_region_classes: 1
              attributes: ''
            bottom:
              wrapper: div
              classes:
                col-sm-12: col-sm-12
              add_region_classes: 1
              attributes: ''
        components:
          62dd7b94-9f49-4b61-ad40-f65d365a7f46:
            uuid: 62dd7b94-9f49-4b61-ad40-f65d365a7f46
            region: top_right
            configuration:
              id: page_title_block
              label: 'Page title'
              provider: core
              label_display: '0'
              context_mapping: {  }
            additional: {  }
            weight: 0
          e58e904b-8890-4559-9582-222b7ca445a9:
            uuid: e58e904b-8890-4559-9582-222b7ca445a9
            region: top_right
            configuration:
              id: local_tasks_block
              label: Tabs
              provider: core
              label_display: '0'
              primary: true
              secondary: true
              context_mapping: {  }
            additional: {  }
            weight: 1
          2ba0359c-af3f-4bd7-a6d6-a6e93f680883:
            uuid: 2ba0359c-af3f-4bd7-a6d6-a6e93f680883
            region: top_right
            configuration:
              id: 'field_block:node:page:body'
              label: Body
              provider: layout_builder
              label_display: '0'
              formatter:
                label: hidden
                type: text_default
                settings: {  }
                third_party_settings: {  }
              context_mapping:
                entity: layout_builder.entity
            additional: {  }
            weight: 2
          e18fc4d1-7588-47ae-97b7-69379a6f2e0d:
            uuid: e18fc4d1-7588-47ae-97b7-69379a6f2e0d
            region: top_left
            configuration:
              id: 'system_menu_block:account'
              label: 'User account menu'
              provider: system
              label_display: visible
              level: 1
              depth: 0
              expand_all_items: false
              context_mapping: {  }
            additional: {  }
            weight: -1
        third_party_settings: {  }
  layout_library:
    enable: true
id: node.landing_page.full
targetEntityType: node
bundle: landing_page
mode: full
content:
  content_moderation_control:
    weight: -20
    settings: {  }
    third_party_settings: {  }
    region: content
  field_meta_tags:
    type: metatag_empty_formatter
    region: content
    weight: 101
    label: above
    settings: {  }
    third_party_settings: {  }
  links:
    weight: 100
    settings: {  }
    third_party_settings: {  }
    region: content
hidden:
  body: true
  field_queue: true
  langcode: true
  layout_builder__layout: true
  layout_builder__translation: true
  layout_selection: true
  panelizer: true
