config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.layout_builder__translation
    - node.type.landing_page
  module:
    - layout_builder_st
id: node.landing_page.layout_builder__translation
field_name: layout_builder__translation
entity_type: node
bundle: landing_page
label: 'Layout Labels'
description: ''
required: false
translatable: true
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: layout_translation
