name: build
on:
  push:
    branches:
      - 5.1.x

# Environment variables available to all jobs and steps in this workflow
env:
  COMPOSER_MEMORY_LIMIT: -1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        db:
         - type: mysql
           port: 3306
         - type: pgsql
           port: 5432

    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@master

    - name: Setup dependencies
      run: |
        git clone --branch 10.1.x https://github.com/drupalwxt/site-wxt.git
        cd site-wxt
        rm composer.lock

    - uses: statcan/actions/composer@master
      with:
        args: require drupalwxt/wxt:5.1.x-dev#${{ github.sha }} --working-dir=./site-wxt

    - name: Build out the Drupal infrastructure
      run: |
        export DB_TYPE=${{ matrix.db.type }}
        export DB_PORT=${{ matrix.db.port }}
        cd site-wxt
        git clone --branch 10.1.x https://github.com/drupalwxt/docker-scaffold.git docker
        make build
        docker compose -f docker-compose.ci.yml up -d
        docker ps -a
        sleep 10

    - name: Run installation and tests
      run: |
        export DB_TYPE=${{ matrix.db.type }}
        export DB_PORT=${{ matrix.db.port }}
        cd site-wxt
        make drupal_install
        make drupal_migrate
        # Change ownership on html/core to allow files to be copied (see drupal_cs in Makefile)
        sudo chown -R $(id -u) html/core
        make test
